sudo: required

services:
  - docker

before_install:
  - docker build -t romi2022/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true romi2022/docker-react npm run test -- --coverage
